In [1]:
pip install numpy


In [2]:
import numpy as np
stock_prices = np.random.randint(100, 501, size=(30, 5))
average_prices = np.mean(stock_prices, axis=0)
max_price = np.max(stock_prices)
max_day, max_company = np.unravel_index(np.argmax(stock_prices), stock_prices.shape)
normalized_prices = (stock_prices - np.min(stock_prices, axis=0)) / (np.max(stock_prices, axis=0) - np.min(stock_prices, axis=0))
risky_investment_days = []
for day in range(30):
    risky_stocks = stock_prices[day] < 200
    if np.any(risky_stocks):
        risky_investment_days.append((day, stock_prices[day][risky_stocks].tolist()))
print("Average stock prices:", average_prices)
print("Highest price recorded:", max_price, "at Day", max_day, "Company", max_company)
print("Normalized prices:", normalized_prices)
print("Risky Investment Days:", risky_investment_days)


Average stock prices: [298.43333333 301.9        315.86666667 284.56666667 290.56666667]
Highest price recorded: 500 at Day 15 Company 0
Normalized prices: [[0.82051282 0.65463918 0.2464986  0.68       0.26861702]
 [0.84358974 0.44329897 0.05882353 0.34133333 0.61170213]
 [0.96410256 0.         0.88515406 1.         0.99202128]
 [0.75384615 0.91752577 0.43417367 0.15733333 0.05585106]
 [0.7025641  0.17525773 0.3977591  0.83733333 0.99202128]
 [0.         0.37886598 0.80952381 0.12533333 0.43617021]
 [0.40769231 0.45103093 0.75630252 0.56533333 0.85106383]
 [0.96923077 0.15721649 0.58823529 0.85066667 0.09308511]
 [0.14871795 0.6443299  0.97759104 0.38133333 0.        ]
 [0.51538462 0.94587629 0.87114846 1.         0.11702128]
 [0.43076923 0.30927835 0.34453782 0.70933333 1.        ]
 [0.33846154 0.01804124 0.59103641 0.048      0.94148936]
 [0.75128205 1.         0.3977591  0.15733333 0.73138298]
 [0.01282051 0.42525773 0.43417367 0.43733333 0.23138298]
 [0.25641026 0.11340206 0.302521