In [3]:
import numpy as np

resources = np.array([
    [15, 40, 32],
    [20, 42, 35],
    [25, 38, 30],
    [18, 50, 40],
    [22, 37, 36],
    [28, 45, 33]
])

total_resources = np.sum(resources, axis=0)
highest_month_idx = np.argmax(np.max(resources, axis=1))
std_devs = np.std(resources, axis=0)
transposed_matrix = resources.T

print("Total resources needed (tons):")
print(f"Oxygen: {total_resources[0]}, Water: {total_resources[1]}, Food: {total_resources[2]}")

print("\nHighest consumption in a month:")
print(f"Water ({np.max(resources[:, 1])} tons) in month {highest_month_idx + 1}")

print("\nStandard deviation of consumption:")
print(f"Oxygen: {std_devs[0]:.1f}, Water: {std_devs[1]:.1f}, Food: {std_devs[2]:.1f}")

print("\nTransposed matrix:")
print(transposed_matrix)


Total resources needed (tons):
Oxygen: 128, Water: 252, Food: 206

Highest consumption in a month:
Water (50 tons) in month 4

Standard deviation of consumption:
Oxygen: 4.3, Water: 4.4, Food: 3.2

Transposed matrix:
[[15 20 25 18 22 28]
 [40 42 38 50 37 45]
 [32 35 30 40 36 33]]
